-- MySQL 8.0+ / MySQL 9.x schema for the e-commerce A/B-test project.
-- Run this whole file in MySQL Workbench before running the Python scripts.

CREATE DATABASE IF NOT EXISTS ecommerce_ab_test
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE ecommerce_ab_test;

-- Metadata for each experiment.
CREATE TABLE IF NOT EXISTS Experiments (
    experiment_id INT NOT NULL AUTO_INCREMENT,
    experiment_name VARCHAR(100) NOT NULL,
    hypothesis TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    PRIMARY KEY (experiment_id)
) ENGINE = InnoDB;

-- Stable assignment of a user to group A or B.
CREATE TABLE IF NOT EXISTS UserAssignments (
    user_id VARCHAR(50) NOT NULL,
    experiment_id INT NOT NULL,
    test_group CHAR(1) NOT NULL,
    assigned_at DATETIME NOT NULL,
    PRIMARY KEY (user_id, experiment_id),
    CONSTRAINT chk_user_assignment_group CHECK (test_group IN ('A', 'B')),
    CONSTRAINT fk_user_assignment_experiment
        FOREIGN KEY (experiment_id)
        REFERENCES Experiments (experiment_id)
        ON DELETE CASCADE
) ENGINE = InnoDB;

-- Raw funnel events generated by the demonstration.
CREATE TABLE IF NOT EXISTS EventLogs (
    event_id BIGINT NOT NULL AUTO_INCREMENT,
    user_id VARCHAR(50) NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    event_timestamp DATETIME NOT NULL,
    device VARCHAR(20) NOT NULL,
    revenue DECIMAL(18, 2) NULL,
    PRIMARY KEY (event_id),
    INDEX idx_eventlogs_user_id (user_id),
    INDEX idx_eventlogs_timestamp (event_timestamp),
    INDEX idx_eventlogs_type (event_type),
    CONSTRAINT chk_event_type
        CHECK (event_type IN ('view', 'add_to_basket', 'checkout', 'purchase'))
) ENGINE = InnoDB;

-- Final statistical results for CR and ARPU.
CREATE TABLE IF NOT EXISTS ExperimentMetrics (
    metric_id INT NOT NULL AUTO_INCREMENT,
    experiment_id INT NOT NULL,
    metric_name VARCHAR(50) NOT NULL,
    control_value DOUBLE NULL,
    variant_value DOUBLE NULL,
    lift DOUBLE NULL,
    p_value DOUBLE NULL,
    is_significant BOOLEAN NOT NULL,
    analysis_date DATETIME NOT NULL,
    sample_size_a INT NOT NULL,
    sample_size_b INT NOT NULL,
    test_duration_days INT NOT NULL,
    notes TEXT NULL,
    PRIMARY KEY (metric_id),
    UNIQUE KEY uq_experiment_metric (experiment_id, metric_name),
    CONSTRAINT fk_metric_experiment
        FOREIGN KEY (experiment_id)
        REFERENCES Experiments (experiment_id)
        ON DELETE CASCADE
) ENGINE = InnoDB;

-- Daily aggregates calculated from EventLogs.
CREATE TABLE IF NOT EXISTS DailyMetrics (
    `date` DATE NOT NULL,
    experiment_id INT NOT NULL,
    test_group CHAR(1) NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    event_count INT NOT NULL,
    unique_users INT NOT NULL,
    total_revenue DECIMAL(18, 2) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`date`, experiment_id, test_group, event_type),
    CONSTRAINT fk_daily_metric_experiment
        FOREIGN KEY (experiment_id)
        REFERENCES Experiments (experiment_id)
        ON DELETE CASCADE
) ENGINE = InnoDB;

-- Running monthly unique-user counts used by the reporting view.
CREATE TABLE IF NOT EXISTS MonthlyCumulativeUniqueUsers (
    `date` DATE NOT NULL,
    experiment_id INT NOT NULL,
    test_group CHAR(1) NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    cumulative_unique_users INT NOT NULL,
    PRIMARY KEY (`date`, experiment_id, test_group, event_type),
    CONSTRAINT fk_cumulative_user_experiment
        FOREIGN KEY (experiment_id)
        REFERENCES Experiments (experiment_id)
        ON DELETE CASCADE
) ENGINE = InnoDB;
